monero-rs/monero-rpc-rs

Cargo.toml, README.md, src/lib.rs, src/models.rs
Creates a new client type `DaemonRpcClient` to interface with the daemon's raw rpc endpoints. The client is slightly refactored to cater to this new client that does not use JsonRpc.
The `get_transactions` method returns a `TransactionResponse` struct. This struct can then be further deserialized to access the hex or json encoded Transaction data.
Add an example to the README for the new endpoint.
=> Add endpoint for get transaction with the daemon rpc

src/lib.rs, src/models.rs
When the wallet rpc is run with `--wallet-dir`, it can manage multiple wallets at a time. This adds two endpoints, one to create a wallet from raw keys (`generate_from_keys`) and another to switch to an existing wallet (`open_wallet`).
=> Add endpoints for opening wallets

.github/workflows/create-release.yml, .github/workflows/draft-new-release.yml, README.md, RELEASING.md
Fix #38 
Reuse the work done in monero-rs. This PR should close some dependabot Actions update.
=> chore: update shared workfow based on monero-rs

.github/workflows/main.yml, tests/docker-compose.yml
Use the latest version of monerod and wallet-rpc. See #48 for later improvements.
=> chore: update test containers

Cargo.toml
Bump monero-rs version to latest release `0.17.0`. This will allow to use the `Amount` with `serde`.
=> chore: update monero to version 0.17.0

.github/workflows/create-release.yml, .github/workflows/draft-new-release.yml
Bump to 2.0.2 to be able to configure the base branch as 'master' instead of 'main'.
=> chore: bump shared workflows to 2.0.2

README.md
Just adds a small section on the readme on how to run the tests, even though it is pretty straighforward.
=> docs(readme): add instructions on how to run tests

CHANGELOG.md, src/models.rs
Closes #42
Decided to remove `SubAddressIndex` instead of `SubaddressIndex` because there are other structs in `models.rs` whose name start with `Subaddress` (with lowercase `a`).
No farcaster project used  `SubAddressIndex`, but I marked the commit with a `!` (as per https://www.conventionalcommits.org/en/v1.0.0/) to indicate that this is possibly a breaking change (in case anyone imported  it in their projects).
=> refactor(models)!: remove duplicated SubAddressIndex

CHANGELOG.md, src/models.rs
This adds basic tests for 
They may seem redundant since there wasn't much to be tested, but having unit tests to make sure things work as expected and no "innocent" change mess up with things, is always good.
=> test(models): add basic tests for models

CHANGELOG.md, src/lib.rs, src/models.rs, tests/rpc.rs
Closes #41 
https://github.com/monero-rs/monero-rs/pull/104 needs to be merged first
=> refactor(models)!: change SubaddressIndex to use subaddress::Index

CHANGELOG.md, src/lib.rs, src/models.rs
=> Use amount from monero-rs

src/models.rs, src/util.rs
=> Feat: Derive Eq where PartialEq is already derived

CHANGELOG.md, Cargo.toml
This removes outdated `time` crate from the dependency tree
=> Disable chrono default features

.github/workflows/test.yml, README.md, tests/clients_tests/basic_wallet.rs, tests/clients_tests/helpers/wallet.rs, tests/docker-compose.yml
Test against latest Monero protocol
=> test: add monero 0.18.1.2 version

CHANGELOG.md, Cargo.toml
Move to next major Monero release in version `0.4.0`
=> fix: rollback monero v0.18

.github/workflows/create-release.yml, .github/workflows/release-to-crates-io.yml
Add the missing job when creating release based on PR merges and bump to latest version the shared workflow.
=> Complete release to crates workflow

CHANGELOG.md, Cargo.toml
#87 got accidentally reverted in #92. This PR cherry picks the commit dc5940aa3fb9041eba5d30c7b1aa4cd8a950eed3 from #87 and update the changelog for the `0.3.2` release.
=> Fix: reintroduced wrongly reverted #87

src/lib.rs, tests/clients_tests/basic_wallet.rs, tests/clients_tests/helpers/wallet.rs
Implemented the methods for storing and retrieving wallet attributes:
https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#set_attribute
https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#get_attribute
=> Added support for the "get_attribute" and "set_attribute" methods

src/lib.rs, src/models.rs, tests/clients_tests/basic_wallet.rs, tests/clients_tests/helpers/wallet.rs
The test I added only checks if the account_index is >=1 since before the implementation of the create_wallet method all wallets were limited to using addresses with account_index = 0. I'm new to the monero ecosystem and its inner working so if there's anything you see that is wrong feel free to change it or message me and I'll do the edit.
=> Added support for the create_wallet rpc method

src/models.rs, tests/clients_tests/all_clients_interaction.rs
Currently calling get_transfers fails with Out=true in the category_selector:
called `Result::unwrap()` on an `Err` value: missing field `suggested_confirmations_threshold`
This change makes `GotTransfer::suggested_confirmations_threshold: Option<u64>`, instead of just `u64`, fixing the issue
=> Fix WalletClient::get_transfers with Out=true in Category Selector

.github/workflows/test.yml, tests/clients_tests/all_clients_interaction.rs, tests/clients_tests/basic_wallet.rs, tests/clients_tests/helpers/wallet.rs
=> Test against monero 0.18.3.3 - 0.18.4.2
